[book]
authors = ["Lex Childs"]
language = "en"
src = "src"
title = "The Welds Book"

[output.html]
git-repository-url = "https://github.com/weldsorm/book"
edit-url-template = "https://github.com/weldsorm/book/edit/main/src/{path}"
